function posCoM = COM_pos_func(in1,in2)
%COM_POS_FUNC
%    POSCOM = COM_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:47

Ms = in2(:,3);
Mth = in2(:,2);
Mtor = in2(:,1);
lth = in2(:,8);
rs = in2(:,12);
rth = in2(:,11);
rtor = in2(:,10);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = cos(x5);
t5 = cos(x6);
t6 = sin(x3);
t7 = sin(x4);
t8 = sin(x5);
t9 = sin(x6);
t10 = lth+rs;
t11 = Ms.*2.0;
t12 = Mth.*2.0;
t13 = t2.*t4;
t14 = t2.*t8;
t15 = t4.*t6;
t16 = t6.*t8;
t17 = t3-1.0;
t18 = t5-1.0;
t20 = Mtor+t11+t12;
t19 = -t16;
t21 = 1.0./t20;
t22 = t14+t15;
t23 = t13+t19;
posCoM = [t21.*(Mtor.*(x1-rtor.*sin(x7))+Ms.*(x1+t10.*(t2.*t7+t3.*t6)-lth.*t2.*t7-lth.*t6.*t17)+Ms.*(x1+t10.*(t5.*t22+t9.*t23)-lth.*t9.*t23-lth.*t18.*t22)+Mth.*(x1+rth.*t6)+Mth.*(x1+rth.*t8)),t21.*(Mtor.*(x2+rtor.*cos(x7))+Ms.*(x2-t10.*(t2.*t3-t6.*t7)-lth.*t6.*t7+lth.*t2.*t17)+Ms.*(x2-t10.*(t5.*t23-t9.*t22)-lth.*t9.*t22+lth.*t18.*t23)+Mth.*(x2-rth.*t2)+Mth.*(x2-rth.*t4))];
