function posFsw = Foot_Sw_pos_func(in1,in2)
%FOOT_SW_POS_FUNC
%    POSFSW = FOOT_SW_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:46

ls = in2(:,9);
lth = in2(:,8);
x1 = in1(1,:);
x2 = in1(2,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = x5+x6;
t3 = cos(t2);
t4 = sin(t2);
posFsw = reshape([t3,t4,0.0,0.0,-t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,x1+ls.*t4+lth.*sin(x5),x2-ls.*t3-lth.*cos(x5),0.0,1.0],[4,4]);
