function out1 = Foot_Sw_Jacobian_Dot_func(in1,in2)
%FOOT_SW_JACOBIAN_DOT_FUNC
%    OUT1 = FOOT_SW_JACOBIAN_DOT_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:52

ls = in2(:,9);
lth = in2(:,8);
x5 = in1(5,:);
x6 = in1(6,:);
x12 = in1(12,:);
x13 = in1(13,:);
t2 = x5+x6;
t3 = x12+x13;
t4 = cos(t2);
t5 = sin(t2);
t6 = ls.*t3.*t4;
t7 = ls.*t3.*t5;
t8 = -t7;
out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t8-lth.*x12.*sin(x5),t6+lth.*x12.*cos(x5),t8,t6,0.0,0.0],[2,7]);
