function out1 = Foot_Sw_Jacobian_func(in1,in2)
%FOOT_SW_JACOBIAN_FUNC
%    OUT1 = FOOT_SW_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:51

ls = in2(:,9);
lth = in2(:,8);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = x5+x6;
t3 = cos(t2);
t4 = sin(t2);
t5 = ls.*t3;
t6 = ls.*t4;
out1 = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t5+lth.*cos(x5),t6+lth.*sin(x5),t5,t6,0.0,0.0],[2,7]);
