function velFst = Foot_St_vel_func(in1,in2)
%FOOT_ST_VEL_FUNC
%    VELFST = FOOT_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:48

ls = in2(:,9);
lth = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
t2 = x3+x4;
t3 = x10+x11;
t4 = cos(t2);
t5 = sin(t2);
t6 = t3.*t4;
t7 = t3.*t5;
t8 = -t7;
velFst = reshape([t8,t6,0.0,0.0,-t6,t8,0.0,0.0,0.0,0.0,0.0,0.0,x8+ls.*t6+lth.*x10.*cos(x3),x9+ls.*t7+lth.*x10.*sin(x3),0.0,0.0],[4,4]);
