function out1 = Foot_St_Jacobian_Dot_func(in1,in2)
%FOOT_ST_JACOBIAN_DOT_FUNC
%    OUT1 = FOOT_ST_JACOBIAN_DOT_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:52

ls = in2(:,9);
lth = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x10 = in1(10,:);
x11 = in1(11,:);
t2 = x3+x4;
t3 = x10+x11;
t4 = cos(t2);
t5 = sin(t2);
t6 = ls.*t3.*t4;
t7 = ls.*t3.*t5;
t8 = -t7;
out1 = reshape([0.0,0.0,0.0,0.0,t8-lth.*x10.*sin(x3),t6+lth.*x10.*cos(x3),t8,t6,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
