function velFsw = Foot_Sw_vel_func(in1,in2)
%FOOT_SW_VEL_FUNC
%    VELFSW = FOOT_SW_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:48

ls = in2(:,9);
lth = in2(:,8);
x5 = in1(5,:);
x6 = in1(6,:);
x8 = in1(8,:);
x9 = in1(9,:);
x12 = in1(12,:);
x13 = in1(13,:);
t2 = x5+x6;
t3 = x12+x13;
t4 = cos(t2);
t5 = sin(t2);
t6 = t3.*t4;
t7 = t3.*t5;
t8 = -t7;
velFsw = reshape([t8,t6,0.0,0.0,-t6,t8,0.0,0.0,0.0,0.0,0.0,0.0,x8+ls.*t6+lth.*x12.*cos(x5),x9+ls.*t7+lth.*x12.*sin(x5),0.0,0.0],[4,4]);
