function posFst = Foot_St_pos_func(in1,in2)
%FOOT_ST_POS_FUNC
%    POSFST = FOOT_ST_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:45

ls = in2(:,9);
lth = in2(:,8);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
posFst = reshape([t3,t4,0.0,0.0,-t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,x1+ls.*t4+lth.*sin(x3),x2-ls.*t3-lth.*cos(x3),0.0,1.0],[4,4]);
