function posHead = Head_pos_func(in1,in2)
%HEAD_POS_FUNC
%    POSHEAD = HEAD_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:46

ltor = in2(:,7);
x1 = in1(1,:);
x2 = in1(2,:);
x7 = in1(7,:);
t2 = cos(x7);
t3 = sin(x7);
posHead = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,x1-ltor.*t3,x2+ltor.*t2,0.0,1.0],[4,4]);
