function posH = Hip_pos_func(in1,in2)
%HIP_POS_FUNC
%    POSH = HIP_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:45

x1 = in1(1,:);
x2 = in1(2,:);
posH = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,x1,x2,0.0,1.0],[4,4]);
