function out1 = Hip_Jacobian_func(in1,in2)
%HIP_JACOBIAN_FUNC
%    OUT1 = HIP_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:51

out1 = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
