function out1 = Hip_Jacobian_Dot_func(in1,in2)
%HIP_JACOBIAN_DOT_FUNC
%    OUT1 = HIP_JACOBIAN_DOT_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:52

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
