function velKsw = Knee_Sw_vel_func(in1,in2)
%KNEE_SW_VEL_FUNC
%    VELKSW = KNEE_SW_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:48

lth = in2(:,8);
x5 = in1(5,:);
x8 = in1(8,:);
x9 = in1(9,:);
x12 = in1(12,:);
t2 = cos(x5);
t3 = sin(x5);
t4 = t2.*x12;
t5 = t3.*x12;
t6 = -t5;
velKsw = reshape([t6,t4,0.0,0.0,-t4,t6,0.0,0.0,0.0,0.0,0.0,0.0,x8+lth.*t4,x9+lth.*t5,0.0,0.0],[4,4]);
