function out1 = Knee_Sw_Jacobian_Dot_func(in1,in2)
%KNEE_SW_JACOBIAN_DOT_FUNC
%    OUT1 = KNEE_SW_JACOBIAN_DOT_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:52

lth = in2(:,8);
x5 = in1(5,:);
x12 = in1(12,:);
out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-lth.*x12.*sin(x5),lth.*x12.*cos(x5),0.0,0.0,0.0,0.0],[2,7]);
