function velKst = Knee_St_vel_func(in1,in2)
%KNEE_ST_VEL_FUNC
%    VELKST = KNEE_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:48

lth = in2(:,8);
x3 = in1(3,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = t2.*x10;
t5 = t3.*x10;
t6 = -t5;
velKst = reshape([t6,t4,0.0,0.0,-t4,t6,0.0,0.0,0.0,0.0,0.0,0.0,x8+lth.*t4,x9+lth.*t5,0.0,0.0],[4,4]);
