function posKst = Knee_St_pos_func(in1,in2)
%KNEE_ST_POS_FUNC
%    POSKST = KNEE_ST_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:45

lth = in2(:,8);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = cos(x3);
t3 = sin(x3);
posKst = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,x1+lth.*t3,x2-lth.*t2,0.0,1.0],[4,4]);
