function out1 = Knee_St_Jacobian_func(in1,in2)
%KNEE_ST_JACOBIAN_FUNC
%    OUT1 = KNEE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:51

lth = in2(:,8);
x3 = in1(3,:);
out1 = reshape([1.0,0.0,0.0,1.0,lth.*cos(x3),lth.*sin(x3),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
