function out1 = Knee_St_Jacobian_Dot_func(in1,in2)
%KNEE_ST_JACOBIAN_DOT_FUNC
%    OUT1 = KNEE_ST_JACOBIAN_DOT_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:52

lth = in2(:,8);
x3 = in1(3,:);
x10 = in1(10,:);
out1 = reshape([0.0,0.0,0.0,0.0,-lth.*x10.*sin(x3),lth.*x10.*cos(x3),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
