function Pe = PE_func(in1,in2)
%PE_FUNC
%    PE = PE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:45

Ms = in2(:,3);
Mth = in2(:,2);
Mtor = in2(:,1);
g = in2(:,13);
lth = in2(:,8);
rs = in2(:,12);
rth = in2(:,11);
rtor = in2(:,10);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = cos(x5);
t5 = cos(x6);
t6 = sin(x3);
t7 = sin(x4);
t8 = sin(x5);
t9 = sin(x6);
t10 = lth+rs;
t11 = t2.*t4;
t12 = t2.*t8;
t13 = t4.*t6;
t14 = t6.*t8;
t15 = -t14;
t16 = t12+t13;
t17 = t11+t15;
Pe = Mth.*g.*(x2-rth.*t2)+Mth.*g.*(x2-rth.*t4)+Ms.*g.*(x2-t10.*(t2.*t3-t6.*t7)+lth.*t2.*(t3-1.0)-lth.*t6.*t7)+Ms.*g.*(x2-t10.*(t5.*t17-t9.*t16)+lth.*t17.*(t5-1.0)-lth.*t9.*t16)+Mtor.*g.*(x2+rtor.*cos(x7));
