function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 10:41:41

Ms = in2(:,3);
Mth = in2(:,2);
Mtor = in2(:,1);
g = in2(:,13);
lth = in2(:,8);
rs = in2(:,12);
rth = in2(:,11);
rtor = in2(:,10);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = cos(x5);
t5 = cos(x6);
t6 = sin(x3);
t7 = sin(x4);
t8 = sin(x5);
t9 = sin(x6);
t10 = lth+rs;
t11 = t2.*t4;
t12 = t2.*t7;
t13 = t3.*t6;
t14 = t2.*t8;
t15 = t4.*t6;
t16 = t6.*t8;
t17 = t5-1.0;
t18 = lth.*t12;
t19 = -t16;
t20 = t12+t13;
t21 = t14+t15;
t22 = t11+t19;
t23 = t5.*t21;
t24 = t10.*t20;
t28 = lth.*t17.*t21;
t25 = t9.*t22;
t26 = -t24;
t27 = lth.*t25;
t29 = t23+t25;
t30 = t10.*t29;
t31 = -t30;
t32 = t27+t28+t31;
t33 = Ms.*g.*t32;
t34 = -t33;
G = [0.0;Ms.*g.*2.0+Mth.*g.*2.0+Mtor.*g;t34-Ms.*g.*(t18+t26+lth.*t6.*(t3-1.0))+Mth.*g.*rth.*t6;-Ms.*g.*(t18+t26+lth.*t13);t34+Mth.*g.*rth.*t8;-Ms.*g.*(t27+t31+lth.*t23);-Mtor.*g.*rtor.*sin(x7)];
