function A = A_DSupp_func(q,qdot)
%A_DSUPP_FUNC
%    ADSUPP = A_DSUPP_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:08

%
global flowdata
params = flowdata.Parameters.Biped.asvec;
x = [q;qdot];
A = [Foot_St_Jacobian_func(x,params);Foot_Sw_Jacobian_func(x,params);];
end