function A = A_Swap_func(q,qdot)
%A_SWAP_FUNC
%    ASWAP = A_SWAP_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:08

%
% global flowdata
% params = flowdata.Parameters.Biped.asvec;
% x = [q;qdot];
% A = Foot_Sw_Jacobian_func(x,params);
A = A_DSupp_func(q,qdot);
end